// Code generated by gen/main.go. DO NOT EDIT.

package v1

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

// Ensure imports are used
var (
	_ = big.NewInt
	_ = common.Address{}
	_ = common.Hash{}
)

// EventName represents an event name from the DTA contracts.
type EventName string

const (
	EventAnswerUpdated                        EventName = "AnswerUpdated"
	EventCCIPMessageRecvFailed                EventName = "CCIPMessageRecvFailed"
	EventDTAAdded                             EventName = "DTAAdded"
	EventDTARemoved                           EventName = "DTARemoved"
	EventDTASettlementClosed                  EventName = "DTASettlementClosed"
	EventDTASettlementOpened                  EventName = "DTASettlementOpened"
	EventDistributorRegistered                EventName = "DistributorRegistered"
	EventDistributorRequestCanceled           EventName = "DistributorRequestCanceled"
	EventDistributorRequestProcessed          EventName = "DistributorRequestProcessed"
	EventDistributorRequestProcessing         EventName = "DistributorRequestProcessing"
	EventEmptyRequestType                     EventName = "EmptyRequestType"
	EventFundAdminRegistered                  EventName = "FundAdminRegistered"
	EventFundTokenAllowlistUpdated            EventName = "FundTokenAllowlistUpdated"
	EventFundTokenRegistered                  EventName = "FundTokenRegistered"
	EventInitialized                          EventName = "Initialized"
	EventInvalidDTARequestSettlement          EventName = "InvalidDTARequestSettlement"
	EventInvalidSubscriptionCrossChainPayment EventName = "InvalidSubscriptionCrossChainPayment"
	EventMessageFailed                        EventName = "MessageFailed"
	EventNativeFundsRecovered                 EventName = "NativeFundsRecovered"
	EventNewRound                             EventName = "NewRound"
	EventOwnershipTransferred                 EventName = "OwnershipTransferred"
	EventRedemptionRequested                  EventName = "RedemptionRequested"
	EventSettlementFailed                     EventName = "SettlementFailed"
	EventSubscriptionRequested                EventName = "SubscriptionRequested"
	EventTokenWithdrawn                       EventName = "TokenWithdrawn"
	EventUnauthorizedSenderDTA                EventName = "UnauthorizedSenderDTA"
	EventUnknown                              EventName = "Unknown"
)

var allEvents = map[string]EventName{
	string(EventAnswerUpdated):                        EventAnswerUpdated,
	string(EventCCIPMessageRecvFailed):                EventCCIPMessageRecvFailed,
	string(EventDTAAdded):                             EventDTAAdded,
	string(EventDTARemoved):                           EventDTARemoved,
	string(EventDTASettlementClosed):                  EventDTASettlementClosed,
	string(EventDTASettlementOpened):                  EventDTASettlementOpened,
	string(EventDistributorRegistered):                EventDistributorRegistered,
	string(EventDistributorRequestCanceled):           EventDistributorRequestCanceled,
	string(EventDistributorRequestProcessed):          EventDistributorRequestProcessed,
	string(EventDistributorRequestProcessing):         EventDistributorRequestProcessing,
	string(EventEmptyRequestType):                     EventEmptyRequestType,
	string(EventFundAdminRegistered):                  EventFundAdminRegistered,
	string(EventFundTokenAllowlistUpdated):            EventFundTokenAllowlistUpdated,
	string(EventFundTokenRegistered):                  EventFundTokenRegistered,
	string(EventInitialized):                          EventInitialized,
	string(EventInvalidDTARequestSettlement):          EventInvalidDTARequestSettlement,
	string(EventInvalidSubscriptionCrossChainPayment): EventInvalidSubscriptionCrossChainPayment,
	string(EventMessageFailed):                        EventMessageFailed,
	string(EventNativeFundsRecovered):                 EventNativeFundsRecovered,
	string(EventNewRound):                             EventNewRound,
	string(EventOwnershipTransferred):                 EventOwnershipTransferred,
	string(EventRedemptionRequested):                  EventRedemptionRequested,
	string(EventSettlementFailed):                     EventSettlementFailed,
	string(EventSubscriptionRequested):                EventSubscriptionRequested,
	string(EventTokenWithdrawn):                       EventTokenWithdrawn,
	string(EventUnauthorizedSenderDTA):                EventUnauthorizedSenderDTA,
}

func parseEventName(value string) (EventName, bool) {
	ev, ok := allEvents[value]
	return ev, ok
}

func (ev EventName) String() string {
	return string(ev)
}

// AnswerUpdated event.
type AnswerUpdated struct {
	Current   *big.Int `json:"current"`
	RoundId   *big.Int `json:"round_id"`
	UpdatedAt *big.Int `json:"updated_at"`
}

// CCIPMessageRecvFailed event.
type CCIPMessageRecvFailed struct {
	MessageId common.Hash `json:"message_id"`
	Reason    []byte      `json:"reason"`
}

// DTAAdded event.
type DTAAdded struct {
	DtaAddr          common.Address `json:"dta_addr"`
	DtaChainSelector uint64         `json:"dta_chain_selector"`
	FundAdminAddr    common.Address `json:"fund_admin_addr"`
	FundTokenId      common.Hash    `json:"fund_token_id"`
	FundTokenAddr    common.Address `json:"fund_token_addr"`
}

// DTARemoved event.
type DTARemoved struct {
	DtaAddr          common.Address `json:"dta_addr"`
	DtaChainSelector uint64         `json:"dta_chain_selector"`
	FundAdminAddr    common.Address `json:"fund_admin_addr"`
	FundTokenId      common.Hash    `json:"fund_token_id"`
}

// DTASettlementClosed event.
type DTASettlementClosed struct {
	FundAdminAddr    common.Address         `json:"fund_admin_addr"`
	FundTokenId      common.Hash            `json:"fund_token_id"`
	RequestType      DistributorRequestType `json:"request_type"`
	DistributorAddr  common.Address         `json:"distributor_addr"`
	DtaChainSelector uint64                 `json:"dta_chain_selector"`
	DtaAddr          common.Address         `json:"dta_addr"`
	RequestId        common.Hash            `json:"request_id"`
	Success          bool                   `json:"success"`
	Err              []byte                 `json:"err"`
}

// DTASettlementOpened event.
type DTASettlementOpened struct {
	FundAdminAddr         common.Address         `json:"fund_admin_addr"`
	FundTokenId           common.Hash            `json:"fund_token_id"`
	RequestType           DistributorRequestType `json:"request_type"`
	DistributorAddr       common.Address         `json:"distributor_addr"`
	DtaChainSelector      uint64                 `json:"dta_chain_selector"`
	DtaAddr               common.Address         `json:"dta_addr"`
	RequestId             common.Hash            `json:"request_id"`
	DistributorWalletAddr common.Address         `json:"distributor_wallet_addr"`
	Shares                *big.Int               `json:"shares"`
	Amount                *big.Int               `json:"amount"`
	Currency              uint8                  `json:"currency"`
}

// DistributorRegistered event.
type DistributorRegistered struct {
	DistributorAddr common.Address `json:"distributor_addr"`
}

// DistributorRequestCanceled event.
type DistributorRequestCanceled struct {
	FundAdminAddr   common.Address `json:"fund_admin_addr"`
	FundTokenId     common.Hash    `json:"fund_token_id"`
	DistributorAddr common.Address `json:"distributor_addr"`
	RequestId       common.Hash    `json:"request_id"`
}

// DistributorRequestProcessed event.
type DistributorRequestProcessed struct {
	RequestId common.Hash   `json:"request_id"`
	Shares    *big.Int      `json:"shares"`
	Status    RequestStatus `json:"status"`
	Error     []byte        `json:"error"`
}

// DistributorRequestProcessing event.
type DistributorRequestProcessing struct {
	FundAdminAddr   common.Address `json:"fund_admin_addr"`
	FundTokenId     common.Hash    `json:"fund_token_id"`
	DistributorAddr common.Address `json:"distributor_addr"`
	RequestId       common.Hash    `json:"request_id"`
	Shares          *big.Int       `json:"shares"`
	Amount          *big.Int       `json:"amount"`
}

// EmptyRequestType event.
type EmptyRequestType struct {
	MessageId common.Hash `json:"message_id"`
	RequestId common.Hash `json:"request_id"`
}

// FundAdminRegistered event.
type FundAdminRegistered struct {
	FundAdminAddr common.Address `json:"fund_admin_addr"`
}

// FundTokenAllowlistUpdated event.
type FundTokenAllowlistUpdated struct {
	FundAdminAddr   common.Address `json:"fund_admin_addr"`
	FundTokenId     common.Hash    `json:"fund_token_id"`
	DistributorAddr common.Address `json:"distributor_addr"`
	Allowed         bool           `json:"allowed"`
}

// FundTokenRegistered event.
type FundTokenRegistered struct {
	FundAdminAddr      common.Address `json:"fund_admin_addr"`
	FundTokenId        common.Hash    `json:"fund_token_id"`
	FundTokenAddr      common.Address `json:"fund_token_addr"`
	NavAddr            common.Address `json:"nav_addr"`
	TokenChainSelector uint64         `json:"token_chain_selector"`
}

// Initialized event.
type Initialized struct {
	Version uint64 `json:"version"`
}

// InvalidDTARequestSettlement event.
type InvalidDTARequestSettlement struct {
	FundAdminAddr                  common.Address `json:"fund_admin_addr"`
	FundTokenId                    common.Hash    `json:"fund_token_id"`
	RequestId                      common.Hash    `json:"request_id"`
	ActualChainSelector            uint64         `json:"actual_chain_selector"`
	ActualDTARequestSettlementAddr common.Address `json:"actual_dta_request_settlement_addr"`
}

// InvalidSubscriptionCrossChainPayment event.
type InvalidSubscriptionCrossChainPayment struct {
	FundAdminAddr              common.Address `json:"fund_admin_addr"`
	FundTokenId                common.Hash    `json:"fund_token_id"`
	RequestId                  common.Hash    `json:"request_id"`
	PaymentTokenDestAddr       common.Address `json:"payment_token_dest_addr"`
	CcipDestTokenAmountsLength *big.Int       `json:"ccip_dest_token_amounts_length"`
	CcipPaymentTokenAddr       common.Address `json:"ccip_payment_token_addr"`
}

// MessageFailed event.
type MessageFailed struct {
	MessageId common.Hash `json:"message_id"`
	Reason    []byte      `json:"reason"`
}

// NativeFundsRecovered event.
type NativeFundsRecovered struct {
	To     common.Address `json:"to"`
	Amount *big.Int       `json:"amount"`
}

// NewRound event.
type NewRound struct {
	RoundId   *big.Int       `json:"round_id"`
	StartedBy common.Address `json:"started_by"`
	StartedAt *big.Int       `json:"started_at"`
}

// OwnershipTransferred event.
type OwnershipTransferred struct {
	PreviousOwner common.Address `json:"previous_owner"`
	NewOwner      common.Address `json:"new_owner"`
}

// RedemptionRequested event.
type RedemptionRequested struct {
	FundAdminAddr   common.Address `json:"fund_admin_addr"`
	FundTokenId     common.Hash    `json:"fund_token_id"`
	DistributorAddr common.Address `json:"distributor_addr"`
	RequestId       common.Hash    `json:"request_id"`
	Shares          *big.Int       `json:"shares"`
	CreatedAt       uint64         `json:"created_at"`
}

// SettlementFailed event.
type SettlementFailed struct {
	FundAdminAddr         common.Address `json:"fund_admin_addr"`
	FundTokenId           common.Hash    `json:"fund_token_id"`
	DistributorAddr       common.Address `json:"distributor_addr"`
	PaymentTokenAddr      common.Address `json:"payment_token_addr"`
	DistributorWalletAddr common.Address `json:"distributor_wallet_addr"`
	RequestId             common.Hash    `json:"request_id"`
	Shares                *big.Int       `json:"shares"`
	Amount                *big.Int       `json:"amount"`
	ErrData               []byte         `json:"err_data"`
}

// SubscriptionRequested event.
type SubscriptionRequested struct {
	FundAdminAddr   common.Address `json:"fund_admin_addr"`
	FundTokenId     common.Hash    `json:"fund_token_id"`
	DistributorAddr common.Address `json:"distributor_addr"`
	RequestId       common.Hash    `json:"request_id"`
	Amount          *big.Int       `json:"amount"`
	CreatedAt       uint64         `json:"created_at"`
}

// TokenWithdrawn event.
type TokenWithdrawn struct {
	Token     common.Address `json:"token"`
	Recipient common.Address `json:"recipient"`
	Amount    *big.Int       `json:"amount"`
}

// UnauthorizedSenderDTA event.
type UnauthorizedSenderDTA struct {
	DtaAddr          common.Address         `json:"dta_addr"`
	DtaChainSelector uint64                 `json:"dta_chain_selector"`
	FundAdminAddr    common.Address         `json:"fund_admin_addr"`
	FundTokenId      common.Hash            `json:"fund_token_id"`
	DistributorAddr  common.Address         `json:"distributor_addr"`
	RequestId        common.Hash            `json:"request_id"`
	ReqType          DistributorRequestType `json:"req_type"`
}
