// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
)

//go:embed DTARequestManagementU.abi.json
var dtaRequestManagementABIJSON string

//go:embed DTARequestSettlementU.abi.json
var dtaRequestSettlementABIJSON string

var (
	dtaRequestManagementABI *abi.ABI
	dtaRequestSettlementABI *abi.ABI
)

func init() {
	var err error

	dtaRequestManagementABI, err = parseABI(dtaRequestManagementABIJSON)
	if err != nil {
		panic(fmt.Sprintf("failed to parse DTARequestManagement ABI: %v", err))
	}

	dtaRequestSettlementABI, err = parseABI(dtaRequestSettlementABIJSON)
	if err != nil {
		panic(fmt.Sprintf("failed to parse DTARequestSettlement ABI: %v", err))
	}

}

func parseABI(jsonABI string) (*abi.ABI, error) {
	parsed, err := abi.JSON(strings.NewReader(jsonABI))
	if err != nil {
		return nil, err
	}
	return &parsed, nil
}

// DTARequestManagementABI returns the parsed DTARequestManagement ABI.
func DTARequestManagementABI() *abi.ABI {
	return dtaRequestManagementABI
}

// DTARequestSettlementABI returns the parsed DTARequestSettlement ABI.
func DTARequestSettlementABI() *abi.ABI {
	return dtaRequestSettlementABI
}
