// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	"fmt"
	"log/slog"

	"github.com/ethereum/go-ethereum/common"
)

// Options defines the configuration for creating a new extension.
type Options struct {
	Logger         *slog.Logger
	AccountAddress string

	DTARequestManagementAddress string

	DTARequestSettlementAddress string
}

func (o *Options) validate() error {
	if !common.IsHexAddress(o.AccountAddress) {
		return fmt.Errorf("invalid AccountAddress: %q", o.AccountAddress)
	}

	if !common.IsHexAddress(o.DTARequestManagementAddress) {
		return fmt.Errorf("invalid DTARequestManagementAddress: %q", o.DTARequestManagementAddress)
	}

	if !common.IsHexAddress(o.DTARequestSettlementAddress) {
		return fmt.Errorf("invalid DTARequestSettlementAddress: %q", o.DTARequestSettlementAddress)
	}

	return nil
}

// Extension provides methods for preparing operations.
type Extension struct {
	logger                      *slog.Logger
	accountAddress              common.Address
	dtaRequestManagementAddress common.Address
	dtaRequestSettlementAddress common.Address
}

// New creates a new extension with the provided options.
func New(opts *Options) (*Extension, error) {
	if opts == nil {
		return nil, fmt.Errorf("options is required")
	}

	if err := opts.validate(); err != nil {
		return nil, fmt.Errorf("invalid options: %w", err)
	}

	logger := opts.Logger
	if logger == nil {
		logger = slog.Default()
	}

	logger.Info("creating CREC SDK extension")

	return &Extension{
		logger:                      logger,
		accountAddress:              common.HexToAddress(opts.AccountAddress),
		dtaRequestManagementAddress: common.HexToAddress(opts.DTARequestManagementAddress),
		dtaRequestSettlementAddress: common.HexToAddress(opts.DTARequestSettlementAddress),
	}, nil
}
