// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"

	"github.com/smartcontractkit/crec-sdk-ext-dta/v2/events"

	transactTypes "github.com/smartcontractkit/crec-sdk/transact/types"
)

var (
	_ = big.NewInt
	_ = common.Address{}
	_ *transactTypes.Operation
)

// PrepareAllowDTAOperation prepares a allowDTA operation on DTARequestSettlement.
func (e *Extension) PrepareAllowDTAOperation(dtaAddr common.Address, dtaChainSelector uint64, fundAdminAddr common.Address, fundTokenId [32]byte, fundTokenAddr common.Address, mintType events.TokenMintType, burnType events.TokenBurnType) (*transactTypes.Operation, error) {
	return e.prepareDTARequestSettlementOp("allowDTA", dtaAddr, dtaChainSelector, fundAdminAddr, fundTokenId, fundTokenAddr, uint8(mintType), uint8(burnType))
}

// PrepareAllowDistributorForTokenOperation prepares a allowDistributorForToken operation on DTARequestManagement.
func (e *Extension) PrepareAllowDistributorForTokenOperation(fundTokenId [32]byte, distributorAddr common.Address) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("allowDistributorForToken", fundTokenId, distributorAddr)
}

// PrepareAuthorizeDistributorForTokenOperation prepares a authorizeDistributorForToken operation on DTARequestManagement.
func (e *Extension) PrepareAuthorizeDistributorForTokenOperation(fundAdminAddr common.Address, fundTokenId [32]byte, distributorAddr common.Address) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("authorizeDistributorForToken", fundAdminAddr, fundTokenId, distributorAddr)
}

// PrepareCancelDistributorRequestOperation prepares a cancelDistributorRequest operation on DTARequestManagement.
func (e *Extension) PrepareCancelDistributorRequestOperation(requestId [32]byte) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("cancelDistributorRequest", requestId)
}

// PrepareCompleteRequestProcessingOperation prepares a completeRequestProcessing operation on DTARequestSettlement.
func (e *Extension) PrepareCompleteRequestProcessingOperation(requestId [32]byte, success bool, err []byte, revertOnErr bool) (*transactTypes.Operation, error) {
	return e.prepareDTARequestSettlementOp("completeRequestProcessing", requestId, success, err, revertOnErr)
}

// PrepareDisableFundTokenOperation prepares a disableFundToken operation on DTARequestManagement.
func (e *Extension) PrepareDisableFundTokenOperation(fundTokenId [32]byte) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("disableFundToken", fundTokenId)
}

// PrepareDisallowDTAOperation prepares a disallowDTA operation on DTARequestSettlement.
func (e *Extension) PrepareDisallowDTAOperation(dtaAddr common.Address, dtaChainSelector uint64, fundAdminAddr common.Address, fundTokenId [32]byte) (*transactTypes.Operation, error) {
	return e.prepareDTARequestSettlementOp("disallowDTA", dtaAddr, dtaChainSelector, fundAdminAddr, fundTokenId)
}

// PrepareDisallowDistributorForTokenOperation prepares a disallowDistributorForToken operation on DTARequestManagement.
func (e *Extension) PrepareDisallowDistributorForTokenOperation(fundTokenId [32]byte, distributorAddr common.Address) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("disallowDistributorForToken", fundTokenId, distributorAddr)
}

// PrepareEnableFundTokenOperation prepares a enableFundToken operation on DTARequestManagement.
func (e *Extension) PrepareEnableFundTokenOperation(fundTokenId [32]byte) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("enableFundToken", fundTokenId)
}

// PrepareProcessDistributorRequestOperation prepares a processDistributorRequest operation on DTARequestManagement.
func (e *Extension) PrepareProcessDistributorRequestOperation(requestId [32]byte) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("processDistributorRequest", requestId)
}

// PrepareRegisterDistributorOperation prepares a registerDistributor operation on DTARequestManagement.
func (e *Extension) PrepareRegisterDistributorOperation(distributorWalletAddr common.Address) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("registerDistributor", distributorWalletAddr)
}

// PrepareRegisterFundAdminOperation prepares a registerFundAdmin operation on DTARequestManagement.
func (e *Extension) PrepareRegisterFundAdminOperation() (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("registerFundAdmin")
}

// PrepareRenounceDTARequestSettlementOwnershipOperation prepares a renounceOwnership operation on DTARequestSettlement.
func (e *Extension) PrepareRenounceDTARequestSettlementOwnershipOperation() (*transactTypes.Operation, error) {
	return e.prepareDTARequestSettlementOp("renounceOwnership")
}

// PrepareRequestRedemptionOperation prepares a requestRedemption operation on DTARequestManagement.
func (e *Extension) PrepareRequestRedemptionOperation(fundAdminAddr common.Address, fundTokenId [32]byte, shares *big.Int, referenceID [32]byte) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("requestRedemption", fundAdminAddr, fundTokenId, shares, referenceID)
}

// PrepareRequestSubscriptionOperation prepares a requestSubscription operation on DTARequestManagement.
func (e *Extension) PrepareRequestSubscriptionOperation(fundAdminAddr common.Address, fundTokenId [32]byte, amount *big.Int, referenceID [32]byte) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("requestSubscription", fundAdminAddr, fundTokenId, amount, referenceID)
}

// PrepareRevokeDistributorForTokenOperation prepares a revokeDistributorForToken operation on DTARequestManagement.
func (e *Extension) PrepareRevokeDistributorForTokenOperation(fundAdminAddr common.Address, fundTokenId [32]byte, distributorAddr common.Address) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("revokeDistributorForToken", fundAdminAddr, fundTokenId, distributorAddr)
}

// PrepareSetManagementCCIPGasLimitOperation prepares a setCCIPGasLimit operation on DTARequestManagement.
func (e *Extension) PrepareSetManagementCCIPGasLimitOperation(gasLimit *big.Int) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("setCCIPGasLimit", gasLimit)
}

// PrepareSetSettlementCCIPGasLimitOperation prepares a setCCIPGasLimit operation on DTARequestSettlement.
func (e *Extension) PrepareSetSettlementCCIPGasLimitOperation(gasLimit *big.Int) (*transactTypes.Operation, error) {
	return e.prepareDTARequestSettlementOp("setCCIPGasLimit", gasLimit)
}

// PrepareTransferDTARequestSettlementOwnershipOperation prepares a transferOwnership operation on DTARequestSettlement.
func (e *Extension) PrepareTransferDTARequestSettlementOwnershipOperation(newOwner common.Address) (*transactTypes.Operation, error) {
	return e.prepareDTARequestSettlementOp("transferOwnership", newOwner)
}

// PrepareWithdrawManagementTokensOperation prepares a withdrawTokens operation on DTARequestManagement.
func (e *Extension) PrepareWithdrawManagementTokensOperation(token common.Address, recipient common.Address, amount *big.Int) (*transactTypes.Operation, error) {
	return e.prepareDTARequestManagementOp("withdrawTokens", token, recipient, amount)
}

// PrepareWithdrawSettlementTokensOperation prepares a withdrawTokens operation on DTARequestSettlement.
func (e *Extension) PrepareWithdrawSettlementTokensOperation(token common.Address, recipient common.Address, amount *big.Int) (*transactTypes.Operation, error) {
	return e.prepareDTARequestSettlementOp("withdrawTokens", token, recipient, amount)
}
