// Code generated by crec-gen. DO NOT EDIT.

package bundle

import "encoding/json"

// ParamsSchemas maps event names to their auto-generated JSON Schema
// derived from the Solidity ABI event parameters.
var ParamsSchemas = map[string]json.RawMessage{
	"DistributorRegistered": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"distributor_addr": {
					"type": "string"
				}
			},
			"required": [
				"distributor_addr"
			]
		}
	`),
	"DistributorRequestCanceled": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"fund_admin_addr": {
					"type": "string"
				},
				"fund_token_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"distributor_addr": {
					"type": "string"
				},
				"request_id": {
					"type": "string",
					"description": "bytes32 hex"
				}
			},
			"required": [
				"fund_admin_addr",
				"fund_token_id",
				"distributor_addr",
				"request_id"
			]
		}
	`),
	"DistributorRequestProcessed": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"request_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"shares": {
					"type": "string",
					"description": "uint256"
				},
				"status": {
					"type": "integer"
				},
				"error": {
					"type": "string",
					"description": "hex bytes"
				}
			},
			"required": [
				"request_id",
				"shares",
				"status",
				"error"
			]
		}
	`),
	"DistributorRequestProcessing": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"fund_admin_addr": {
					"type": "string"
				},
				"fund_token_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"distributor_addr": {
					"type": "string"
				},
				"request_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"shares": {
					"type": "string",
					"description": "uint256"
				},
				"amount": {
					"type": "string",
					"description": "uint256"
				}
			},
			"required": [
				"fund_admin_addr",
				"fund_token_id",
				"distributor_addr",
				"request_id",
				"shares",
				"amount"
			]
		}
	`),
	"FundAdminRegistered": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"fund_admin_addr": {
					"type": "string"
				}
			},
			"required": [
				"fund_admin_addr"
			]
		}
	`),
	"FundTokenAllowlistUpdated": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"fund_admin_addr": {
					"type": "string"
				},
				"fund_token_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"distributor_addr": {
					"type": "string"
				},
				"allowed": {
					"type": "boolean"
				}
			},
			"required": [
				"fund_admin_addr",
				"fund_token_id",
				"distributor_addr",
				"allowed"
			]
		}
	`),
	"FundTokenRegistered": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"fund_admin_addr": {
					"type": "string"
				},
				"fund_token_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"fund_token_addr": {
					"type": "string"
				},
				"nav_addr": {
					"type": "string"
				},
				"token_chain_selector": {
					"type": "string",
					"description": "uint64"
				}
			},
			"required": [
				"fund_admin_addr",
				"fund_token_id",
				"fund_token_addr",
				"nav_addr",
				"token_chain_selector"
			]
		}
	`),
	"RedemptionRequested": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"fund_admin_addr": {
					"type": "string"
				},
				"fund_token_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"distributor_addr": {
					"type": "string"
				},
				"reference_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"request_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"shares": {
					"type": "string",
					"description": "uint256"
				},
				"created_at": {
					"type": "integer"
				}
			},
			"required": [
				"fund_admin_addr",
				"fund_token_id",
				"distributor_addr",
				"reference_id",
				"request_id",
				"shares",
				"created_at"
			]
		}
	`),
	"SubscriptionRequested": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"fund_admin_addr": {
					"type": "string"
				},
				"fund_token_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"distributor_addr": {
					"type": "string"
				},
				"reference_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"request_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"amount": {
					"type": "string",
					"description": "uint256"
				},
				"created_at": {
					"type": "integer"
				}
			},
			"required": [
				"fund_admin_addr",
				"fund_token_id",
				"distributor_addr",
				"reference_id",
				"request_id",
				"amount",
				"created_at"
			]
		}
	`),
	"DTASettlementOpened": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"fund_admin_addr": {
					"type": "string"
				},
				"fund_token_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"request_type": {
					"type": "integer"
				},
				"distributor_addr": {
					"type": "string"
				},
				"dta_chain_selector": {
					"type": "string",
					"description": "uint64"
				},
				"dta_addr": {
					"type": "string"
				},
				"request_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"distributor_wallet_addr": {
					"type": "string"
				},
				"shares": {
					"type": "string",
					"description": "uint256"
				},
				"amount": {
					"type": "string",
					"description": "uint256"
				},
				"currency": {
					"type": "integer"
				}
			},
			"required": [
				"fund_admin_addr",
				"fund_token_id",
				"request_type",
				"distributor_addr",
				"dta_chain_selector",
				"dta_addr",
				"request_id",
				"distributor_wallet_addr",
				"shares",
				"amount",
				"currency"
			]
		}
	`),
	"DTASettlementClosed": json.RawMessage(`
		{
			"type": "object",
			"properties": {
				"fund_admin_addr": {
					"type": "string"
				},
				"fund_token_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"request_type": {
					"type": "integer"
				},
				"distributor_addr": {
					"type": "string"
				},
				"dta_chain_selector": {
					"type": "string",
					"description": "uint64"
				},
				"dta_addr": {
					"type": "string"
				},
				"request_id": {
					"type": "string",
					"description": "bytes32 hex"
				},
				"success": {
					"type": "boolean"
				},
				"err": {
					"type": "string",
					"description": "hex bytes"
				}
			},
			"required": [
				"fund_admin_addr",
				"fund_token_id",
				"request_type",
				"distributor_addr",
				"dta_chain_selector",
				"dta_addr",
				"request_id",
				"success",
				"err"
			]
		}
	`),
}
