// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
)

//go:embed FeeManagerU.abi.json
var feeManagerABIJSON string

var (
	feeManagerABI *abi.ABI
)

func init() {
	var err error

	feeManagerABI, err = parseABI(feeManagerABIJSON)
	if err != nil {
		panic(fmt.Sprintf("failed to parse FeeManager ABI: %v", err))
	}

}

func parseABI(jsonABI string) (*abi.ABI, error) {
	parsed, err := abi.JSON(strings.NewReader(jsonABI))
	if err != nil {
		return nil, err
	}
	return &parsed, nil
}

// FeeManagerABI returns the parsed FeeManager ABI.
func FeeManagerABI() *abi.ABI {
	return feeManagerABI
}
