// Code generated by crec-gen. DO NOT EDIT.

package operations

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"

	"github.com/smartcontractkit/crec-sdk-ext-dta/v2/fee_manager/events"

	transactTypes "github.com/smartcontractkit/crec-sdk/transact/types"
)

var (
	_ = big.NewInt
	_ = common.Address{}
	_ *transactTypes.Operation
)

// PrepareAddSupportedFeeTokenOperation prepares a addSupportedFeeToken operation on FeeManager.
func (e *Extension) PrepareAddSupportedFeeTokenOperation(feeTokenAddr common.Address, tokenType events.FeeTokenType, priceFeedAddr common.Address, feeTokenDecimals uint8) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("addSupportedFeeToken", feeTokenAddr, uint8(tokenType), priceFeedAddr, feeTokenDecimals)
}

// PrepareAllowProductForActionOperation prepares a allowProductForAction operation on FeeManager.
func (e *Extension) PrepareAllowProductForActionOperation(productAddr common.Address, actionId [32]byte, feeTokenAddr common.Address) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("allowProductForAction", productAddr, actionId, feeTokenAddr)
}

// PrepareChargeFeeOperation prepares a chargeFee operation on FeeManager.
func (e *Extension) PrepareChargeFeeOperation(actionId [32]byte, productRequestId [32]byte) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("chargeFee", actionId, productRequestId)
}

// PrepareCreateUserTokenAccountOperation prepares a createUserTokenAccount operation on FeeManager.
func (e *Extension) PrepareCreateUserTokenAccountOperation(feeTokenAddr common.Address) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("createUserTokenAccount", feeTokenAddr)
}

// PrepareDisallowProductForActionOperation prepares a disallowProductForAction operation on FeeManager.
func (e *Extension) PrepareDisallowProductForActionOperation(productAddr common.Address, actionId [32]byte, feeTokenAddr common.Address) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("disallowProductForAction", productAddr, actionId, feeTokenAddr)
}

// PrepareRecoverExcessBalanceOperation prepares a recoverExcessBalance operation on FeeManager.
func (e *Extension) PrepareRecoverExcessBalanceOperation(feeTokenAddr common.Address, to common.Address, amount *big.Int) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("recoverExcessBalance", feeTokenAddr, to, amount)
}

// PrepareRefundFeeOperation prepares a refundFee operation on FeeManager.
func (e *Extension) PrepareRefundFeeOperation(actionId [32]byte, productRequestId [32]byte) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("refundFee", actionId, productRequestId)
}

// PrepareReserveAndChargeFee1DOperation prepares a reserveAndChargeFee1D operation on FeeManager.
func (e *Extension) PrepareReserveAndChargeFee1DOperation(prevActionId [32]byte, actionId [32]byte, productRequestId [32]byte, userAddr common.Address, discountId1 [32]byte) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("reserveAndChargeFee1D", prevActionId, actionId, productRequestId, userAddr, discountId1)
}

// PrepareReserveFee1DOperation prepares a reserveFee1D operation on FeeManager.
func (e *Extension) PrepareReserveFee1DOperation(actionId [32]byte, productRequestId [32]byte, userAddr common.Address, discountCode1 [32]byte) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("reserveFee1D", actionId, productRequestId, userAddr, discountCode1)
}

// PrepareReserveFeeOperation prepares a reserveFee operation on FeeManager.
func (e *Extension) PrepareReserveFeeOperation(actionId [32]byte, productRequestId [32]byte, userAddr common.Address, discountCodes [][32]byte) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("reserveFee", actionId, productRequestId, userAddr, discountCodes)
}

// PrepareSetActionFeeOperation prepares a setActionFee operation on FeeManager.
func (e *Extension) PrepareSetActionFeeOperation(actionId [32]byte, fee *big.Int) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("setActionFee", actionId, fee)
}

// PrepareSetDiscountOperation prepares a setDiscount operation on FeeManager.
func (e *Extension) PrepareSetDiscountOperation(discountId [32]byte, discountPercent uint16) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("setDiscount", discountId, discountPercent)
}

// PrepareTopupERC20UserTokenAccountOperation prepares a topupERC20UserTokenAccount operation on FeeManager.
func (e *Extension) PrepareTopupERC20UserTokenAccountOperation(userAddr common.Address, feeTokenAddr common.Address, amount *big.Int) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("topupERC20UserTokenAccount", userAddr, feeTokenAddr, amount)
}

// PrepareTopupNativeUserTokenAccountOperation prepares a topupNativeUserTokenAccount operation on FeeManager.
func (e *Extension) PrepareTopupNativeUserTokenAccountOperation(userAddr common.Address) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("topupNativeUserTokenAccount", userAddr)
}

// PrepareUpdateSupportedFeeTokenOperation prepares a updateSupportedFeeToken operation on FeeManager.
func (e *Extension) PrepareUpdateSupportedFeeTokenOperation(feeTokenAddr common.Address, priceFeedAddr common.Address) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("updateSupportedFeeToken", feeTokenAddr, priceFeedAddr)
}

// PrepareWithdrawAvailableBalanceOperation prepares a withdrawAvailableBalance operation on FeeManager.
func (e *Extension) PrepareWithdrawAvailableBalanceOperation(feeTokenAddr common.Address, to common.Address) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("withdrawAvailableBalance", feeTokenAddr, to)
}

// PrepareWithdrawBalanceOperation prepares a withdrawBalance operation on FeeManager.
func (e *Extension) PrepareWithdrawBalanceOperation(feeTokenAddr common.Address, to common.Address, amount *big.Int) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("withdrawBalance", feeTokenAddr, to, amount)
}

// PrepareWithdrawNativeBalanceOperation prepares a withdrawNativeBalance operation on FeeManager.
func (e *Extension) PrepareWithdrawNativeBalanceOperation(to common.Address, amount *big.Int) (*transactTypes.Operation, error) {
	return e.prepareFeeManagerOp("withdrawNativeBalance", to, amount)
}
