// Code generated by crec-gen. DO NOT EDIT.

package events

import (
	"fmt"
	"strconv"

	"github.com/ethereum/go-ethereum/common"
	"github.com/smartcontractkit/crec-sdk/parsing"
)

var (
	_ = fmt.Sprintf
	_ = strconv.ParseBool
	_ = common.Address{}
	_ = parsing.ScientificNotationToBigInt
)

// ConcreteEvent represents any decoded concrete event payload.
type ConcreteEvent interface{}

// EventDecoder is a function that decodes event parameters into a concrete event type.
type EventDecoder func(params map[string]string, txHash string) (ConcreteEvent, error)

// eventDecoders maps event names to their decoder functions.
var eventDecoders = map[EventName]EventDecoder{
	EventActionFeeSet:               decodeActionFeeSet,
	EventDiscountSet:                decodeDiscountSet,
	EventExcessBalanceRecovered:     decodeExcessBalanceRecovered,
	EventFeeCharged:                 decodeFeeCharged,
	EventFeeTokenFeeAfterConversion: decodeFeeTokenFeeAfterConversion,
	EventFiatFeeAfterDiscount:       decodeFiatFeeAfterDiscount,
	EventNoActionFeeSet:             decodeNoActionFeeSet,
	EventNoAvailableBalance:         decodeNoAvailableBalance,
	EventNoRequestFee:               decodeNoRequestFee,
	EventProductAllowed:             decodeProductAllowed,
	EventSupportedFeeTokenAdded:     decodeSupportedFeeTokenAdded,
	EventSupportedFeeTokenUpdated:   decodeSupportedFeeTokenUpdated,
	EventUserTokenAccountCreated:    decodeUserTokenAccountCreated,
	EventUserTokenAccountRefunded:   decodeUserTokenAccountRefunded,
	EventUserTokenAccountToppedUp:   decodeUserTokenAccountToppedUp,
	EventUserTokenAccountWithdrawn:  decodeUserTokenAccountWithdrawn,
}

// EventDecoders returns the map of event decoders.
func EventDecoders() map[EventName]EventDecoder {
	return eventDecoders
}

func decodeActionFeeSet(params map[string]string, _ string) (ConcreteEvent, error) {
	fee, err := parsing.ScientificNotationToBigInt(params["fee"])
	if err != nil {
		return nil, fmt.Errorf("parse fee %q: %w", params["fee"], err)
	}
	return &ActionFeeSet{
		ActionId: common.HexToHash(params["action_id"]),
		Fee:      fee,
	}, nil
}

func decodeDiscountSet(params map[string]string, _ string) (ConcreteEvent, error) {
	discount, err := parsing.ScientificNotationToUint16(params["discount"])
	if err != nil {
		return nil, fmt.Errorf("parse discount %q: %w", params["discount"], err)
	}
	return &DiscountSet{
		DiscountId: common.HexToHash(params["discount_id"]),
		Discount:   discount,
	}, nil
}

func decodeExcessBalanceRecovered(params map[string]string, _ string) (ConcreteEvent, error) {
	amount, err := parsing.ScientificNotationToBigInt(params["amount"])
	if err != nil {
		return nil, fmt.Errorf("parse amount %q: %w", params["amount"], err)
	}
	return &ExcessBalanceRecovered{
		UserAddr:  common.HexToAddress(params["user_addr"]),
		TokenAddr: common.HexToAddress(params["token_addr"]),
		Amount:    amount,
	}, nil
}

func decodeFeeCharged(params map[string]string, _ string) (ConcreteEvent, error) {
	amount, err := parsing.ScientificNotationToBigInt(params["amount"])
	if err != nil {
		return nil, fmt.Errorf("parse amount %q: %w", params["amount"], err)
	}
	return &FeeCharged{
		UserAddr:  common.HexToAddress(params["user_addr"]),
		TokenAddr: common.HexToAddress(params["token_addr"]),
		ActionId:  common.HexToHash(params["action_id"]),
		Amount:    amount,
	}, nil
}

func decodeFeeTokenFeeAfterConversion(params map[string]string, _ string) (ConcreteEvent, error) {
	initialFiatFee, err := parsing.ScientificNotationToBigInt(params["initial_fiat_fee"])
	if err != nil {
		return nil, fmt.Errorf("parse initial_fiat_fee %q: %w", params["initial_fiat_fee"], err)
	}
	fiatFeeAfterDiscount, err := parsing.ScientificNotationToBigInt(params["fiat_fee_after_discount"])
	if err != nil {
		return nil, fmt.Errorf("parse fiat_fee_after_discount %q: %w", params["fiat_fee_after_discount"], err)
	}
	exchangeRate, err := parsing.ScientificNotationToBigInt(params["exchange_rate"])
	if err != nil {
		return nil, fmt.Errorf("parse exchange_rate %q: %w", params["exchange_rate"], err)
	}
	feeTokenFee, err := parsing.ScientificNotationToBigInt(params["fee_token_fee"])
	if err != nil {
		return nil, fmt.Errorf("parse fee_token_fee %q: %w", params["fee_token_fee"], err)
	}
	return &FeeTokenFeeAfterConversion{
		InitialFiatFee:       initialFiatFee,
		FiatFeeAfterDiscount: fiatFeeAfterDiscount,
		ExchangeRate:         exchangeRate,
		FeeTokenFee:          feeTokenFee,
	}, nil
}

func decodeFiatFeeAfterDiscount(params map[string]string, _ string) (ConcreteEvent, error) {
	initialFiatFee, err := parsing.ScientificNotationToBigInt(params["initial_fiat_fee"])
	if err != nil {
		return nil, fmt.Errorf("parse initial_fiat_fee %q: %w", params["initial_fiat_fee"], err)
	}
	fiatFeeAfterDiscount, err := parsing.ScientificNotationToBigInt(params["fiat_fee_after_discount"])
	if err != nil {
		return nil, fmt.Errorf("parse fiat_fee_after_discount %q: %w", params["fiat_fee_after_discount"], err)
	}
	maxProductDiscount, err := parsing.ScientificNotationToBigInt(params["max_product_discount"])
	if err != nil {
		return nil, fmt.Errorf("parse max_product_discount %q: %w", params["max_product_discount"], err)
	}
	return &FiatFeeAfterDiscount{
		InitialFiatFee:       initialFiatFee,
		FiatFeeAfterDiscount: fiatFeeAfterDiscount,
		MaxProductDiscount:   maxProductDiscount,
	}, nil
}

func decodeNoActionFeeSet(params map[string]string, _ string) (ConcreteEvent, error) {
	return &NoActionFeeSet{
		ActionId: common.HexToHash(params["action_id"]),
	}, nil
}

func decodeNoAvailableBalance(params map[string]string, _ string) (ConcreteEvent, error) {
	return &NoAvailableBalance{
		UserAddr:  common.HexToAddress(params["user_addr"]),
		TokenAddr: common.HexToAddress(params["token_addr"]),
	}, nil
}

func decodeNoRequestFee(params map[string]string, _ string) (ConcreteEvent, error) {
	return &NoRequestFee{
		ActionId:  common.HexToHash(params["action_id"]),
		RequestId: common.HexToHash(params["request_id"]),
	}, nil
}

func decodeProductAllowed(params map[string]string, _ string) (ConcreteEvent, error) {
	return &ProductAllowed{
		ProductAddr:  common.HexToAddress(params["product_addr"]),
		ActionId:     common.HexToHash(params["action_id"]),
		FeeTokenAddr: common.HexToAddress(params["fee_token_addr"]),
	}, nil
}

func decodeSupportedFeeTokenAdded(params map[string]string, _ string) (ConcreteEvent, error) {
	tokenType, err := parsing.ScientificNotationToUint8(params["token_type"])
	if err != nil {
		return nil, fmt.Errorf("parse token_type %q: %w", params["token_type"], err)
	}
	return &SupportedFeeTokenAdded{
		FeeTokenAddr:  common.HexToAddress(params["fee_token_addr"]),
		TokenType:     FeeTokenType(tokenType),
		PriceFeedAddr: common.HexToAddress(params["price_feed_addr"]),
	}, nil
}

func decodeSupportedFeeTokenUpdated(params map[string]string, _ string) (ConcreteEvent, error) {
	tokenType, err := parsing.ScientificNotationToUint8(params["token_type"])
	if err != nil {
		return nil, fmt.Errorf("parse token_type %q: %w", params["token_type"], err)
	}
	priceFeedDecimals, err := parsing.ScientificNotationToUint8(params["price_feed_decimals"])
	if err != nil {
		return nil, fmt.Errorf("parse price_feed_decimals %q: %w", params["price_feed_decimals"], err)
	}
	return &SupportedFeeTokenUpdated{
		FeeTokenAddr:      common.HexToAddress(params["fee_token_addr"]),
		TokenType:         FeeTokenType(tokenType),
		PriceFeedAddr:     common.HexToAddress(params["price_feed_addr"]),
		PriceFeedDecimals: priceFeedDecimals,
	}, nil
}

func decodeUserTokenAccountCreated(params map[string]string, _ string) (ConcreteEvent, error) {
	tokenType, err := parsing.ScientificNotationToUint8(params["token_type"])
	if err != nil {
		return nil, fmt.Errorf("parse token_type %q: %w", params["token_type"], err)
	}
	return &UserTokenAccountCreated{
		UserAddr:           common.HexToAddress(params["user_addr"]),
		TokenAddr:          common.HexToAddress(params["token_addr"]),
		UserTokenAccountId: common.HexToHash(params["user_token_account_id"]),
		TokenType:          FeeTokenType(tokenType),
	}, nil
}

func decodeUserTokenAccountRefunded(params map[string]string, _ string) (ConcreteEvent, error) {
	amount, err := parsing.ScientificNotationToBigInt(params["amount"])
	if err != nil {
		return nil, fmt.Errorf("parse amount %q: %w", params["amount"], err)
	}
	return &UserTokenAccountRefunded{
		UserAddr:  common.HexToAddress(params["user_addr"]),
		TokenAddr: common.HexToAddress(params["token_addr"]),
		Amount:    amount,
	}, nil
}

func decodeUserTokenAccountToppedUp(params map[string]string, _ string) (ConcreteEvent, error) {
	amount, err := parsing.ScientificNotationToBigInt(params["amount"])
	if err != nil {
		return nil, fmt.Errorf("parse amount %q: %w", params["amount"], err)
	}
	return &UserTokenAccountToppedUp{
		UserAddr:  common.HexToAddress(params["user_addr"]),
		TokenAddr: common.HexToAddress(params["token_addr"]),
		Amount:    amount,
	}, nil
}

func decodeUserTokenAccountWithdrawn(params map[string]string, _ string) (ConcreteEvent, error) {
	amount, err := parsing.ScientificNotationToBigInt(params["amount"])
	if err != nil {
		return nil, fmt.Errorf("parse amount %q: %w", params["amount"], err)
	}
	return &UserTokenAccountWithdrawn{
		UserAddr:  common.HexToAddress(params["user_addr"]),
		TokenAddr: common.HexToAddress(params["token_addr"]),
		Amount:    amount,
	}, nil
}
