// Code generated by crec-gen. DO NOT EDIT.

package events

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

var (
	_ = big.NewInt
	_ = common.Address{}
	_ = common.Hash{}
)

// EventName represents an event name from the contracts.
type EventName string

const (
	EventActionFeeSet               EventName = "ActionFeeSet"
	EventDiscountSet                EventName = "DiscountSet"
	EventExcessBalanceRecovered     EventName = "ExcessBalanceRecovered"
	EventFeeCharged                 EventName = "FeeCharged"
	EventFeeTokenFeeAfterConversion EventName = "FeeTokenFeeAfterConversion"
	EventFiatFeeAfterDiscount       EventName = "FiatFeeAfterDiscount"
	EventNoActionFeeSet             EventName = "NoActionFeeSet"
	EventNoAvailableBalance         EventName = "NoAvailableBalance"
	EventNoRequestFee               EventName = "NoRequestFee"
	EventProductAllowed             EventName = "ProductAllowed"
	EventSupportedFeeTokenAdded     EventName = "SupportedFeeTokenAdded"
	EventSupportedFeeTokenUpdated   EventName = "SupportedFeeTokenUpdated"
	EventUserTokenAccountCreated    EventName = "UserTokenAccountCreated"
	EventUserTokenAccountRefunded   EventName = "UserTokenAccountRefunded"
	EventUserTokenAccountToppedUp   EventName = "UserTokenAccountToppedUp"
	EventUserTokenAccountWithdrawn  EventName = "UserTokenAccountWithdrawn"
	EventUnknown                    EventName = "Unknown"
)

var allEvents = map[string]EventName{
	string(EventActionFeeSet):               EventActionFeeSet,
	string(EventDiscountSet):                EventDiscountSet,
	string(EventExcessBalanceRecovered):     EventExcessBalanceRecovered,
	string(EventFeeCharged):                 EventFeeCharged,
	string(EventFeeTokenFeeAfterConversion): EventFeeTokenFeeAfterConversion,
	string(EventFiatFeeAfterDiscount):       EventFiatFeeAfterDiscount,
	string(EventNoActionFeeSet):             EventNoActionFeeSet,
	string(EventNoAvailableBalance):         EventNoAvailableBalance,
	string(EventNoRequestFee):               EventNoRequestFee,
	string(EventProductAllowed):             EventProductAllowed,
	string(EventSupportedFeeTokenAdded):     EventSupportedFeeTokenAdded,
	string(EventSupportedFeeTokenUpdated):   EventSupportedFeeTokenUpdated,
	string(EventUserTokenAccountCreated):    EventUserTokenAccountCreated,
	string(EventUserTokenAccountRefunded):   EventUserTokenAccountRefunded,
	string(EventUserTokenAccountToppedUp):   EventUserTokenAccountToppedUp,
	string(EventUserTokenAccountWithdrawn):  EventUserTokenAccountWithdrawn,
}

// ParseEventName converts a string to an EventName if recognized.
func ParseEventName(value string) (EventName, bool) {
	ev, ok := allEvents[value]
	return ev, ok
}

func (ev EventName) String() string {
	return string(ev)
}

// ActionFeeSet event.
type ActionFeeSet struct {
	ActionId common.Hash `json:"action_id"`
	Fee      *big.Int    `json:"fee"`
}

// DiscountSet event.
type DiscountSet struct {
	DiscountId common.Hash `json:"discount_id"`
	Discount   uint16      `json:"discount"`
}

// ExcessBalanceRecovered event.
type ExcessBalanceRecovered struct {
	UserAddr  common.Address `json:"user_addr"`
	TokenAddr common.Address `json:"token_addr"`
	Amount    *big.Int       `json:"amount"`
}

// FeeCharged event.
type FeeCharged struct {
	UserAddr  common.Address `json:"user_addr"`
	TokenAddr common.Address `json:"token_addr"`
	ActionId  common.Hash    `json:"action_id"`
	Amount    *big.Int       `json:"amount"`
}

// FeeTokenFeeAfterConversion event.
type FeeTokenFeeAfterConversion struct {
	InitialFiatFee       *big.Int `json:"initial_fiat_fee"`
	FiatFeeAfterDiscount *big.Int `json:"fiat_fee_after_discount"`
	ExchangeRate         *big.Int `json:"exchange_rate"`
	FeeTokenFee          *big.Int `json:"fee_token_fee"`
}

// FiatFeeAfterDiscount event.
type FiatFeeAfterDiscount struct {
	InitialFiatFee       *big.Int `json:"initial_fiat_fee"`
	FiatFeeAfterDiscount *big.Int `json:"fiat_fee_after_discount"`
	MaxProductDiscount   *big.Int `json:"max_product_discount"`
}

// NoActionFeeSet event.
type NoActionFeeSet struct {
	ActionId common.Hash `json:"action_id"`
}

// NoAvailableBalance event.
type NoAvailableBalance struct {
	UserAddr  common.Address `json:"user_addr"`
	TokenAddr common.Address `json:"token_addr"`
}

// NoRequestFee event.
type NoRequestFee struct {
	ActionId  common.Hash `json:"action_id"`
	RequestId common.Hash `json:"request_id"`
}

// ProductAllowed event.
type ProductAllowed struct {
	ProductAddr  common.Address `json:"product_addr"`
	ActionId     common.Hash    `json:"action_id"`
	FeeTokenAddr common.Address `json:"fee_token_addr"`
}

// SupportedFeeTokenAdded event.
type SupportedFeeTokenAdded struct {
	FeeTokenAddr  common.Address `json:"fee_token_addr"`
	TokenType     FeeTokenType   `json:"token_type"`
	PriceFeedAddr common.Address `json:"price_feed_addr"`
}

// SupportedFeeTokenUpdated event.
type SupportedFeeTokenUpdated struct {
	FeeTokenAddr      common.Address `json:"fee_token_addr"`
	TokenType         FeeTokenType   `json:"token_type"`
	PriceFeedAddr     common.Address `json:"price_feed_addr"`
	PriceFeedDecimals uint8          `json:"price_feed_decimals"`
}

// UserTokenAccountCreated event.
type UserTokenAccountCreated struct {
	UserAddr           common.Address `json:"user_addr"`
	TokenAddr          common.Address `json:"token_addr"`
	UserTokenAccountId common.Hash    `json:"user_token_account_id"`
	TokenType          FeeTokenType   `json:"token_type"`
}

// UserTokenAccountRefunded event.
type UserTokenAccountRefunded struct {
	UserAddr  common.Address `json:"user_addr"`
	TokenAddr common.Address `json:"token_addr"`
	Amount    *big.Int       `json:"amount"`
}

// UserTokenAccountToppedUp event.
type UserTokenAccountToppedUp struct {
	UserAddr  common.Address `json:"user_addr"`
	TokenAddr common.Address `json:"token_addr"`
	Amount    *big.Int       `json:"amount"`
}

// UserTokenAccountWithdrawn event.
type UserTokenAccountWithdrawn struct {
	UserAddr  common.Address `json:"user_addr"`
	TokenAddr common.Address `json:"token_addr"`
	Amount    *big.Int       `json:"amount"`
}
